### ISSUE TITLE
Complete docker-compose.yaml

### ISSUE THREAD

**Issue by dani8art** [aws1617-groups/aws1617-groups#10]

**Comment by dani8art** [comment]
```
version: '2'
services:
  mongodb:
    container_name: mongodb-container
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata:
```
